### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by stianjensen** [ninjadev/nin#120]
We first need to decide on a license for the project, and then get approval from everyone who has contributed code to nin up until now.

**Comment by sigvef** [comment]
Apache 2?

**Comment by stianjensen** [comment]
Sound good

**Comment by stianjensen** [comment]
We need approval from:

- [x] @stianjensen
- [ ] @sigvef 
- [ ] @lionleaf 
- [ ] @aleksanb 
- [ ] @peterhgombos 
- [ ] @cristeahub 
- [ ] @iver56

**Comment by cristeahub** [comment]
:+1:

**Comment by stianjensen** [comment]
@aleksanb ping

**Comment by aleksanb** [comment]
Why apache2 vs MIT ?

**Comment by stianjensen** [comment]
Mostly more explicit terms regarding trademarks:

> Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

http://choosealicense.com/licenses/apache-2.0/

**Comment by aleksanb** [comment]
:+1:
