### ISSUE TITLE
Toggling developer tools in firefox makes demo screen black.

### ISSUE THREAD

**Issue by aleksanb** [ninjadev/nin#145]

**Comment by stianjensen** [comment]
Can you try reverting https://github.com/ninjadev/nin/commit/f4b750c15694f63576d129e1af0ca97b672f4dbb and see if that resolves the issue?

**Comment by aleksanb** [comment]
Reverting did not fix the issue.
Okey so it turns out that the renderer 'breaks' if i change the height of firefox, and therefore the rendertarget. Changing the width works fine.
Have we changed some of the resize-code recently?

**Comment by stianjensen** [comment]
https://github.com/ninjadev/nin/commit/c58e6e7866c73fb9b269601eccb781827cf79b49

**Comment by aleksanb** [comment]
Checkouting to that commit did indeed fix the resize issues (couldn't revert the commit due to other conflicts appearing).
@sigvef who wrote it, any reccomendations for fix?

**Comment by sigvef** [comment]
Does the window resize event fire?

**Comment by aleksanb** [comment]
How do I check that?

**Comment by stianjensen** [comment]
```
window.addEventListener('resize', function(){console.log('Yolooooooo!');});
