### ISSUE TITLE
Control nin using media keys

### ISSUE THREAD

**Issue by iver56** [ninjadev/nin#166]
Using media keys, one can start/pause the demo without even leaving the IDE. Also, the "previous" and "next" media key could be mapped respectively to skip 5 (or 10)? seconds back and ahead.

This node package can listen to media keys. The events can be passed on as commands to the frontend over websockets:
https://www.npmjs.com/package/mediakeys

Alternatively, one may use a variant of this Chrome plugin, but that means that it'll only work in Chrome and one needs the plugin:
https://github.com/borismus/keysocket

Waddya think? Useful or not?

**Comment by stianjensen** [comment]
I think it's a cool feature, and the best version would be via websockets – no extra setup required \o/

However, I do think this should be an opt-in feature, as you sometimes may want to use your media keys for controlling spotify etc. while working.

**Comment by sigvef** [comment]
Nice feature :D 

> I do think this should be an opt-in feature

.ninrc \o/

**Comment by iver56** [comment]
> .ninrc \o/

Or it could be a setting in the menu? Preferences could be stored in localStorage

**Comment by sigvef** [comment]
localStorage is not cross-browser though, so you need to copy your settings if you use two browsers.

**Comment by sigvef** [comment]
.ninrc can still be modified by clicking in nin's menus :)

**Comment by iver56** [comment]
True. That would make .ninrc user-specific and not project-specific. Is that what we want?

**Comment by cristeahub** [comment]
> .ninrc should belong to nin

Working on it as we speak: https://github.com/ninjadev/nin/issues/167

**Comment by iver56** [comment]
> .ninrc

> Working on it

JSON format?

**Comment by cristeahub** [comment]
>> .ninrc

> ...

What do you mean here?

>> Working on it

> JSON format?

Yes.

**Comment by iver56** [comment]
:+1: 

> What do you mean here?

Nothing special. It was meant to indicate that I snipped some text out (to avoid quoting everything)

**Comment by cristeahub** [comment]
Ahh, right. Seemed like you had a comment on the .ninrc thing ^^

**Comment by aleksanb** [comment]
Closing for now.
Please open a PR if the need arises again 💃 🗡 🗡 👯
