### ISSUE TITLE
Self defined keybindings in user settings

### ISSUE THREAD

**Issue by cristeahub** [ninjadev/nin#167]
Add a system for us to add our own key bindings.

**Comment by iver56** [comment]
Would this work globally or just when the web browser is in focus?

**Comment by sigvef** [comment]
Hm, perhaps we want global shortcuts?

**Comment by cristeahub** [comment]
I don't find global shortcuts that compelling to be honest, so I'll make it the way we have now. It can be iterated upon later of course.

**Comment by aleksanb** [comment]
Closing for now as part of the great issue cleanup of 11/10/2016.
