### ISSUE TITLE
.jshintrc not found

### ISSUE THREAD

**Issue by cristeahub** [ninjadev/nin#186]
This comes up as an error from time to time when running grunt. Should this file have been included?

**Comment by stianjensen** [comment]
Yup, we should include a common .jshintrc file in the project.

I have created my own locally, and I believe @sigvef has done the same thing

**Comment by cristeahub** [comment]
Could you send me your jshint file, and I'll make a prq, or you can just make a prq yourself :)

**Comment by cristeahub** [comment]
If not we can just use this one: https://gist.github.com/connor/1597131

**Comment by iver56** [comment]
So we're going to use jshint instead of google closure linter? If that's the case, then README.md should be updated accordingly.
________________________________

**Comment by stianjensen** [comment]
@iver56 the readme should be updated to clarify things, yes.

The idea is that jshint is used for the frontend project (see the gruntfile which already relies on jshint).

Google Closure Linter applies to the demo code and dasBoot because that code will be compiled with google closure compiler

**Comment by cristeahub** [comment]
> @iver56 the readme should be updated to clarify things, yes.
> 
> The idea is that jshint is used for the frontend project (see the gruntfile which already relies on jshint).
> 
> Google Closure Linter applies to the demo code and dasBoot because that code will be compiled with google closure compiler

I'll add readme information!
