### ISSUE TITLE
Lock down frontend folder version numbers

### ISSUE THREAD

**Issue by stianjensen** [ninjadev/nin#205]
All version numbers should be set to a specific version, otherwise Bad Things™ will probably happen.

**Comment by stianjensen** [comment]
I've tried working through this, but it's one hell of a mess. Most of the package versions we have now are early unstable releases that are two years old.

I'll try to do it incrementally, and simultaneously update and freeze version numbers of packages. First the easy ones, and then, hopefully, tackle the grunt v1.0 bump and all of its dependencies (it was not trivial).

**Comment by sigvef** [comment]
If grunt is a non-trivial update, perhaps we should consider switching to something newer/better/hipper instead?
