### ISSUE TITLE
Nin compile broken

### ISSUE THREAD

**Issue by stianjensen** [ninjadev/nin#216]
After testing old versions of nin, I've narrowed it down to this commit: 4016f96

Compiling with nin before that commit results in a working demo, but anything after that (remember to run `npm install`) will make the loading bar stop at 100% but no start button appear.
No errors in the console.

When not using png-compression the demo works fine.

System: OS X
Node: v6.1.0

**Comment by sigvef** [comment]
Which demo are you compiling? The default index.html loader does not have a loading bar. Perhaps there is an issue in the index.html you are using? If you can, upload a broken .png.html so I can take a look too!

**Comment by stianjensen** [comment]
stianj.com/broken.png.html -> This is the master branch of ninjacon-invite compiled with the master branch of nin

**Comment by stianjensen** [comment]
Node version 6.1.0, btw

**Comment by stianjensen** [comment]
The crc update from 2.0.0 to 3.4.0 seems to be the reason.

**Comment by stianjensen** [comment]
Related? https://github.com/alexgorbatchev/node-crc/issues/27
