### ISSUE TITLE
Switch to iTXt from tEXt formats in PNG metadata

### ISSUE THREAD

**Issue by aleksanb** [ninjadev/nin#251]
tEXt formats only support latin-1, so no emojis for us.
Standards document is here: http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html.
I gave up after trying to implement it turned rather hairy, and even after figuring out a solution i was unable to find a png viewer that could display itxt chunks.

**Comment by stianjensen** [comment]
Since implementation is hairy and no png viewers can actually view itxt, should we rather just keep the tEXt format?

**Comment by aleksanb** [comment]
Closing for now. Can look at it again during next release cycle.
