### ISSUE TITLE
Horizontal zooming

### ISSUE THREAD

**Issue by stianjensen** [ninjadev/nin#258]
With #254, horizontal zooming is broken. Considering the current feature set of node-based nin, horizontal zoom doesn't seem very useful, so it might be best to simply remove the feature altogether.

On the other hand, new timeline-based features might be introduced later, making zooming useful again. Still, we can always just create a new zoom-system when it's needed (since the current one is broken anyway).

I suggest we simply remove it for now.

**Comment by sigvef** [comment]
> I suggest we simply remove it for now.

+1
