### ISSUE TITLE
Input nodes do not render their inputs properly

### ISSUE THREAD

**Issue by sigvef** [ninjadev/nin#273]
afaict there should be in input box (similar to the output boxes) here:

![image](https://cloud.githubusercontent.com/assets/578029/20222697/9a051462-a836-11e6-9df9-799c20a5c381.png)

**Comment by sigvef** [comment]
Like this:

![image](https://cloud.githubusercontent.com/assets/578029/20222710/a98e752c-a836-11e6-8aeb-4b77a64b855b.png)

**Comment by stianjensen** [comment]
As far as I can see in graphEditor.js now, there's only nodeGroup and outputGroup. Might it have disappeared in a rebase?
