### ISSUE TITLE
`nin new` should add template .gitignore file

### ISSUE THREAD

**Issue by stianjensen** [ninjadev/nin#319]
After running `nin new` I get the following with git status:
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
	gen/
	index.html
	nin.json
	res/
	src/
```

At least `gen` should be in the gitignore file. Also `bin` is a folder we want to gitignore

**Comment by aleksanb** [comment]
But it does, @stianjensen! You must have removed it when removing the .git subdirectory in the /re repository!

**Comment by aleksanb** [comment]
**
![image](https://cloud.githubusercontent.com/assets/1413365/23869380/0b7b2a0e-0823-11e7-955c-8ac3b7756b54.png)
**
