### ISSUE TITLE
Unused nodes are highlighted in the graph

### ISSUE THREAD

**Issue by cristeahub** [ninjadev/nin#368]
In our re-demo the greet scene was highlighted from the start, which is not where it's shown. Not sure what the reasoning is for it, but I'll leave this issue here for further investigation later on.
![image](https://cloud.githubusercontent.com/assets/1488921/24837671/b19f85da-1d39-11e7-9a09-d40482b4f959.png)

**Comment by stianjensen** [comment]
Might have been a bug in the implementation of the TextureMultiplexerNode inside github.com/ninjadev/re

**Comment by sigvef** [comment]
Yeah that was just becuase `H_and_a_half` was never disactivated. I fixed it earlier this week iirc.
