### ISSUE TITLE
Cannot read property 'outputs' of undefined.

### ISSUE THREAD

**Issue by skftn** [ninjadev/nin#389]
Having some troubles starting out with a new project. I'm not sure if I'm suppose to get this error:

![e](http://i.imgur.com/iZH2u0j.png)

I did the following:

    npm install -g ninjadev-nin
    nin new penis
    cd penis
    nin run

Running on Node 7.9.0 (npm 4.2.0) x64 Debian jessie.

**Comment by defcon8** [comment]
same issue here..

**Comment by stianjensen** [comment]
Thanks for the report @skftn, will publish a new version in a couple of hours that resolves this!

**Comment by aleksanb** [comment]
A fixed version should be published on npm now.

**Comment by defcon8** [comment]
Fix works! thanks!
