### ISSUE TITLE
[Windows 10, Node 7.8] "nin new <name>" creates directory, but no files

### ISSUE THREAD

**Issue by kristianpedersen** [ninjadev/nin#396]
Windows 10 Home, version 1703 build 15063.138
Node 7.8.0
nin 14.0.0
git 2.10.2.windows.1

When I run "nin new myProjectName", it creates a new directory, and then tells me "Initialized empty Git repository".

However, there aren't any files inside the folder that gets created by "nin new <name>".
Entering "nin run" in the newly created folder just makes the command prompt freeze.

Running cmd as admin doesn't have any effect.

**Comment by stianjensen** [comment]
Thanks for the report! It turns out we're calling `cp` to copy files over to the new project, which obviously doesn't work on windows! I'll create a patch for this.

**Comment by stianjensen** [comment]
We fixed this in #400, which is live on npm as version 15.0.0 now!
