### ISSUE TITLE
Key shortcuts overlay

### ISSUE THREAD

**Issue by iver56** [ninjadev/nin#80]
Have a "help" button that shows an overlay with all the key shortcuts. Alternatively, it would make sense to have a menu bar that exposes the various functions.

**Comment by iver56** [comment]
https://github.com/ninjadev/nin/pull/141

**Comment by stianjensen** [comment]
Yeah, no, we still don't have this

https://github.com/ninjadev/nin/pull/141/files#diff-e20a0dd121e96af4143d006abb41eaa1R23

**Comment by iver56** [comment]
But the menu is already populated with most functions, and it also shows the key shortcut for each function, and that's basically all we need, right?
https://github.com/ninjadev/nin/pull/142

**Comment by stianjensen** [comment]
That's a good point
