### ISSUE TITLE
Camera controllers are broken

### ISSUE THREAD

**Issue by cristeahub** [ninjadev/nin#85]
The fly around-system is currently broken.
![image](https://cloud.githubusercontent.com/assets/1488921/8513680/407221c0-2375-11e5-87b2-ebb630e3d17f.png)

**Comment by stianjensen** [comment]
Only when your selected layer does not use the cameracontroller. It's always been like that, unfortunately

**Comment by stianjensen** [comment]
fly-around is now opened up to all layers with a `this.camera` property, while previously it also required a `this.cameraController`. This should help make it less "broken".
